ssh_username        = "packer"
image_name          = "centos"
source_image_family = "centos-stream-8"
project_id          = "csye6225-cloud-dev-414620"
zone                = "us-east1-b"
network             = "default"
