# This is a basic workflow to help you get started with Actions

name: Packer for GCP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "packer-build"
  packer-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
            credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Generate application artifact
        run: zip -r webapp.zip ./
      
      # - name: Upload the artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: my-artifact
      #     path: ./webapp.zip

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.10.1"

      - name: Run `packer init`
        id: init
        run: packer init packer/.
      
      - name: Run `packer fmt`
        id: fmt
        run: packer fmt packer/.

      - name: Run `packer validate`
        id: validate
        run: packer validate -var-file='dev.pkrvars.hcl' .
